services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "true"
      MOD_PLATFORM: AUTO_CURSEFORGE
      # allocate from https://console.curseforge.com/ and set in .env file
      CF_API_KEY: ${CF_API_KEY}
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/better-mc-forge-bmc4/files/6628107
      MEMORY: 10G
      ONLINE_MODE: FALSE
      SPAWN_PROTECTION: 0
    volumes:
      - mc-data:/data

volumes:
  mc-data: {}